import {
  IconBook2,
  IconBuildingStore,
  IconCalendarWeek,
  IconCoin,
  IconHome,
  IconMap,
  IconPackage,
  IconReportMoney,
  IconReportAnalytics,
  IconSettingsAutomation,
  IconShoppingCart,
  IconTractor,
  IconUsersGroup,
  IconTrees,
  IconMap2,
  IconBox,
  IconBuildings,
} from "@tabler/icons-react";
import { PATH } from "./path.constants";

export const NAV_BAR = [
  {
    label: "Trang chủ",
    icon: IconHome,
    link: PATH.HOME,
  },
  {
    label: "Lịch trình",
    icon: IconCalendarWeek,
    link: PATH.SCHEDULE,
  },
  {
    label: "Quản lý vùng trồng",
    icon: IconMap,
    link: PATH.AREA_MANAGEMENT,
    children: [
      { label: "Khu vực canh tác", link: PATH.AREA_REGION },
      // { label: "Khu vực", link: PATH.AREA_ZONE },
      // { label: "Lô canh tác", link: PATH.AREA_BLOCK },
      // { label: "Hàng", link: PATH.AREA_ROW },
      { label: "Cây canh tác", link: PATH.AREA_TREE },
      { label: "Loại đất", link: PATH.AREA_SOIL },
      { label: "Phương pháp canh tác", link: PATH.AREA_CULTIVATION_METHOD },
      { label: "Lịch sử", link: PATH.AREA_HISTORY },
    ],
  },
  {
    label: "Quản lý biểu đồ",
    icon: IconMap2,
    link: PATH.MAP_REGION,
    children: [
      { label: "Phân bổ vùng", link: PATH.MAP_REGION },
      { label: "Phân bổ khu vực", link: PATH.MAP_AREA },
      { label: "Phân bổ lô", link: PATH.MAP_PLOT },
      { label: "Bản đồ địa chính", link: PATH.MAP_MAP },
      { label: "Địa hình", link: PATH.MAP_TERRAIN },
    ],
  },
  {
    label: "Quản lý cây trồng",
    icon: IconTrees,
    link: PATH.PLANT_MANAGEMENT,
    children: [
      { label: "Nhóm cây trồng", link: PATH.PLANT_GROUP },
      { label: "Danh mục cây trồng", link: PATH.PLANT_CATALOG },
      { label: "Giống cây", link: PATH.PLANT_VARIETY },
      { label: "Hạt giống", link: PATH.PLANT_SEED },
      { label: "Cây trồng", link: PATH.PLANT_TREE },
      { label: "Tài liệu kỹ thuật", link: PATH.PLANT_TECHNICAL_DOC },
    ],
  },
  {
    label: "Quản lý mùa vụ & chu kỳ",
    icon: IconReportAnalytics,
    link: PATH.SEASON_MANAGEMENT,
    children: [
      { label: "Mùa vụ", link: PATH.SEASON_GROWTH },
      { label: "Chu kỳ", link: PATH.SEASON_CYCLE },
    ],
  },
  {
    label: "Quản lý kế hoạch",
    icon: IconSettingsAutomation,
    link: PATH.PLAN_MANAGEMENT,
    children: [
      { label: "Kế hoạch", link: PATH.PLAN_MAIN },
      { label: "Phân công việc", link: PATH.PLAN_ASSIGN },
      { label: "Giao việc phát sinh", link: PATH.PLAN_UNPLANNED },
      { label: "Lịch sử", link: PATH.PLAN_HISTORY },
    ],
  },
  {
    label: "Quản lý công việc",
    icon: IconBook2,
    link: PATH.TASK_MANAGEMENT,
    children: [
      { label: "Công việc phát sinh", link: PATH.TASK_MAIN },
      { label: "Công việc BATMAN", link: PATH.TASK_BATMAN },
    ],
  },
  {
    label: "Quản lý thu hoạch",
    icon: IconReportAnalytics,
    link: PATH.HARVEST_MANAGEMENT,
    children: [
      { label: "Báo cáo thu hoạch", link: PATH.HARVEST_REPORT },
      { label: "Truy vấn cây theo bản đồ", link: PATH.HARVEST_QUERY },
    ],
  },
  {
    label: "Quản lý sản phẩm",
    icon: IconPackage,
    link: PATH.PRODUCT_MANAGEMENT,
    children: [
      { label: "Danh mục sản phẩm", link: PATH.PRODUCT_TYPE },
      { label: "Sản phẩm", link: PATH.PRODUCT_ITEM },
      {
        label: "Danh mục nguyên vật liệu",
        link: PATH.PRODUCT_RAW_MATERIAL_TYPE,
      },
      { label: "Nguyên vật liệu", link: PATH.PRODUCT_RAW_MATERIAL },
    ],
  },
  {
    label: "Quản lý hợp đồng",
    icon: IconReportMoney,
    link: PATH.CONTRACT_MANAGEMENT,
    children: [
      { label: "Hợp đồng mua bán", link: PATH.CONTRACT_SALE },
      { label: "Hợp đồng trao đổi", link: PATH.CONTRACT_EXCHANGE },
      { label: "Hợp đồng cho tặng", link: PATH.CONTRACT_GIFT },
      { label: "Hợp đồng vay", link: PATH.CONTRACT_LOAN },
      { label: "Hợp đồng thuê", link: PATH.CONTRACT_RENT },
      { label: "Hợp đồng mượn", link: PATH.CONTRACT_BORROW },
      { label: "Hợp đồng dịch vụ", link: PATH.CONTRACT_SERVICE },
      { label: "Hợp đồng vận chuyển", link: PATH.CONTRACT_TRANSPORT },
      { label: "Hợp đồng gia công", link: PATH.CONTRACT_PROCESSING },
      { label: "Hợp đồng gửi giữ tài sản", link: PATH.CONTRACT_STORAGE },
      { label: "Hợp đồng ủy quyền", link: PATH.CONTRACT_AUTHORIZATION },
      { label: "Hợp đồng hợp tác", link: PATH.CONTRACT_PARTNERSHIP },
    ],
  },
  {
    label: "Quản lý nhân sự",
    icon: IconUsersGroup,
    link: PATH.HR_MANAGEMENT,
    children: [
      { label: "Phòng ban", link: PATH.HR_DEPARTMENT },
      { label: "Vị trí", link: PATH.HR_POSITION },
      { label: "Đội nhóm", link: PATH.HR_TEAM },
      { label: "Nhân sự", link: PATH.HR_EMPLOYEE },
    ],
  },
  // {
  //   label: "Quản lý nhà máy",
  //   icon: IconBuildingFactory,
  //   link: PATH.FACTORY_MANAGEMENT,
  //   children: [
  //     { label: "Nhà máy", link: PATH.FACTORY_MAIN },
  //     { label: "Lịch sử chỉnh sửa", link: PATH.FACTORY_HISTORY },
  //   ],
  // },
  {
    label: "Quản lý máy móc",
    icon: IconTractor,
    link: PATH.MACHINE_MANAGEMENT,
    children: [
      { label: "Danh mục máy móc", link: PATH.MACHINE_TYPE },
      { label: "Máy móc", link: PATH.MACHINE_MAIN },
      { label: "Lịch sử sử dụng", link: PATH.MACHINE_USAGE_HISTORY },
      { label: "Lịch sử bảo trì", link: PATH.MACHINE_MAINTENANCE_HISTORY },
      { label: "Lịch sử thanh lý", link: PATH.MACHINE_DISPOSAL_HISTORY },
    ],
  },
  {
    label: "Thuốc BVTV",
    icon: IconPackage,
    link: PATH.PESTICIDE_MANAGEMENT,
    children: [
      { label: "Danh mục thuốc", link: PATH.PESTICIDE_CATEGORY },
      { label: "Thuốc", link: PATH.PESTICIDE_MAIN },
      { label: "Lịch sử sử dụng", link: PATH.PESTICIDE_HISTORY },
      { label: "Lịch sử huỷ", link: PATH.PESTICIDE_DISPOSAL_HISTORY },
    ],
  },
  {
    label: "Quản lý vật tư",
    icon: IconPackage,
    link: PATH.SUPPLY_MANAGEMENT,
    children: [
      { label: "Danh mục vật tư", link: PATH.SUPPLY_TYPE },
      { label: "Vật tư", link: PATH.SUPPLY_MAIN },
      { label: "Lịch sử sử dụng", link: PATH.SUPPLY_HISTORY },
      { label: "Lịch sử thanh lý", link: PATH.SUPPLY_DISPOSAL_HISTORY },
    ],
  },
  {
    label: "Quản lý phân bón",
    icon: IconBox,
    link: "12123",
    children: [
      { label: "Danh mục phân bón", link: PATH.FERTILIZER_TYPE },
      { label: "Phân bón", link: PATH.FERTILIZER_MAIN },
      { label: "Lịch sử sử dụng", link: PATH.FERTILIZER_HISTORY },
      { label: "Lịch sử huỷ", link: PATH.FERTILIZER_DISPOSAL_HISTORY },
    ],
  },
  {
    label: "Quản lý thu mua",
    icon: IconBuildingStore,
    link: PATH.PURCHASE_MANAGEMENT,
    children: [
      { label: "Sản phẩm", link: PATH.PURCHASE_MANAGEMENT_PRODUCT },
      { label: "Nguyên vật liệu", link: PATH.PURCHASE_MANAGEMENT_RAW_MATERIAL },
    ],
  },
  {
    label: "Quản lý đặt hàng",
    icon: IconShoppingCart,
    link: PATH.ORDER_MANAGEMENT,
    children: [
      {
        label: "Đặt hàng nhanh",
        link: PATH.ORDER_MANAGEMENT_QUICK,
      },
      {
        label: "Đặt hàng (đăng nhập)",
        link: PATH.ORDER_MANAGEMENT_LOGGED_IN,
      },
    ],
  },
  {
    label: "Quản lý kho",
    icon: IconCoin,
    link: PATH.STOCK_MANAGEMENT,
    children: [
      { label: "Khu vực quản lý", link: PATH.STOCK_AREA },
      { label: "Kho vận", link: PATH.STOCK_DELIVERY },
      { label: "Xuất/nhập vật tư", link: PATH.STOCK_SUPPLY },
      { label: "Xuất/nhập thuốc", link: PATH.STOCK_PESTICIDE },
      { label: "Xuất/nhập máy móc", link: PATH.STOCK_MACHINE },
      { label: "Xuất/nhập hạt giống", link: PATH.STOCK_SEED },
      { label: "Xuất/nhập phân bón", link: PATH.STOCK_FERTILIZER },
    ],
  },
  {
    label: "Doanh nghiệp / Hộ nông dân",
    icon: IconBuildings,
    link: PATH.COMPANY,
    children: [
      {
        label: "Nhà cung cấp",
        link: PATH.COMPANY,
      },
      {
        label: "Khách hàng",
        link: PATH.COMPANY_CUSTOMER,
      },
      {
        label: "Đối tác",
        link: PATH.COMPANY_PARTNER,
      },
    ],
  },
  // {
  //   label: "Quản lý nhà cung cấp",
  //   icon: IconBuildingWarehouse,
  //   link: PATH.VENDOR,
  // },
  {
    label: "Mua hàng",
    icon: IconShoppingCart,
    link: PATH.PURCHASE,
  },
  {
    label: "Bán hàng",
    icon: IconBuildingStore,
    link: PATH.SELL,
  },
  {
    label: "Tài chính & Kế toán",
    icon: IconReportMoney,
    link: PATH.FINANCE_ACCOUNT,
  },
];
